/** 视觉工坊玩法二级选项，与网页 PLAYBOOK_VARIANT_CONFIGS / 业态覆盖对齐 */
const PLAYBOOK_VARIANT_CONFIGS = {
  festival_promo: {
    pickerLabel: '选择节日',
    options: [
      {
        id: 'spring_festival',
        label: '春节',
        periodLabel: '2026年2月17日—3月3日（正月初一至十五）',
        headline: '春节团圆宴',
        subheadline: '年夜饭/聚会套餐预订',
        offer: '满300减80',
        timeRange: '2026年2月17日—3月3日',
        note: '恭贺新春 · 需提前预约',
        styleId: 'guochao',
      },
      {
        id: 'valentine',
        label: '情人节',
        periodLabel: '2月14日',
        headline: '情人节双人餐',
        subheadline: '浪漫氛围 · 限量席位',
        offer: '双人套餐¥199',
        timeRange: '2月14日当天',
        note: '可赠甜品/玫瑰',
      },
      {
        id: 'dragon_boat',
        label: '端午节',
        periodLabel: '2026年5月31日（农历五月初五）',
        headline: '端午安康 · 节日限定',
        subheadline: '粽子礼盒/聚餐套餐',
        offer: '满200减50',
        timeRange: '2026年5月29日—5月31日',
        note: '端午安康',
        styleId: 'guochao',
      },
      {
        id: 'qixi',
        label: '七夕',
        periodLabel: '2026年8月19日（农历七月初七）',
        headline: '七夕约会首选',
        subheadline: '双人浪漫套餐',
        offer: '8.8折',
        timeRange: '2026年8月19日前后3天',
        note: '提前预约更省心',
      },
      {
        id: 'mid_autumn',
        label: '中秋节',
        periodLabel: '2026年9月25日（农历八月十五）',
        headline: '中秋团圆宴',
        subheadline: '月饼礼盒 + 聚餐套餐',
        offer: '满200减50',
        timeRange: '2026年9月24日—9月26日',
        note: '团圆/送礼皆宜',
        styleId: 'guochao',
      },
      {
        id: 'national_day',
        label: '国庆节',
        periodLabel: '10月1日—10月7日',
        headline: '国庆狂欢',
        subheadline: '假期聚会 · 全家通用',
        offer: '节日专享8.8折',
        timeRange: '10月1日—10月7日',
        note: '假期正常营业',
      },
      {
        id: 'double11',
        label: '双11',
        periodLabel: '11月11日',
        headline: '双11限时钜惠',
        subheadline: '全年最低价',
        offer: '5折起',
        timeRange: '11月10日—11月12日',
        note: '售完即止',
      },
      {
        id: 'new_year',
        label: '元旦',
        periodLabel: '1月1日—1月3日',
        headline: '元旦迎新',
        subheadline: '跨年/开年聚餐',
        offer: '满100减20',
        timeRange: '1月1日—1月3日',
        note: '新年快乐',
      },
    ],
  },
  flash_sale: {
    pickerLabel: '秒杀时段',
    options: [
      {
        id: 'tonight_8',
        label: '今晚8点',
        periodLabel: '今日 20:00—24:00',
        headline: '今晚8点秒杀',
        subheadline: '准时开抢 · 手慢无',
        offer: '5折起',
        timeRange: '今日 20:00—24:00',
        note: '售完即止',
      },
      {
        id: 'weekend',
        label: '周末专场',
        periodLabel: '周六日全天',
        headline: '周末限时秒杀',
        subheadline: '仅限周末',
        offer: '立减30元',
        timeRange: '周六日 10:00—22:00',
      },
      {
        id: 'lunch',
        label: '午间闪购',
        periodLabel: '11:00—14:00',
        headline: '午市秒杀',
        subheadline: '工作日午间专享',
        offer: '买一送一',
        timeRange: '工作日 11:00—14:00',
      },
      {
        id: 'clearance',
        label: '清仓特惠',
        periodLabel: '售完即止',
        headline: '清仓最后一批',
        subheadline: '库存告急',
        offer: '3折起',
        timeRange: '售完即止',
        note: '不退不换',
      },
    ],
  },
  group_buy_new: {
    pickerLabel: '套餐规格',
    options: [
      {
        id: 'double',
        label: '双人餐',
        periodLabel: '2人适用',
        headline: '超值双人餐',
        subheadline: '含招牌菜+饮品',
        offer: '¥99双人餐',
        timeRange: '周末通用',
        note: '免预约',
      },
      {
        id: 'triple',
        label: '3-4人餐',
        periodLabel: '3-4人适用',
        headline: '3-4人欢聚餐',
        subheadline: '分量足 · 性价比高',
        offer: '¥168/3-4人',
        timeRange: '午晚市通用',
      },
      {
        id: 'family',
        label: '家庭套餐',
        periodLabel: '4-6人适用',
        headline: '家庭聚餐套餐',
        subheadline: '老少皆宜',
        offer: '¥199家庭餐',
        timeRange: '全天可用',
        note: '可外带',
      },
      {
        id: 'lunch_set',
        label: '午市套餐',
        periodLabel: '11:00—14:00',
        headline: '午市工作餐',
        subheadline: '上菜快 · 管饱',
        offer: '¥39起',
        timeRange: '工作日 11:00—14:00',
      },
    ],
  },
  grand_opening: {
    pickerLabel: '开业阶段',
    options: [
      {
        id: 'soft_open',
        label: '试营业',
        periodLabel: '试营业期间',
        headline: '试营业福利',
        subheadline: '前100名到店有礼',
        offer: '首单8折',
        timeRange: '试营业期间',
        note: '欢迎提意见',
      },
      {
        id: 'grand',
        label: '正式开业',
        periodLabel: '开业当天',
        headline: '盛大开业',
        subheadline: '打卡拍照送小食',
        offer: '满50减20',
        timeRange: '开业当天及前后3天',
        styleId: 'lively',
      },
      {
        id: 'anniversary',
        label: '周年庆',
        periodLabel: '店庆期间',
        headline: '周年庆感恩回馈',
        subheadline: '老客专享',
        offer: '全场8.8折',
        timeRange: '店庆周',
        note: '感谢一路相伴',
      },
    ],
  },
  store_visit: {
    pickerLabel: '种草角度',
    options: [
      {
        id: 'ambiance',
        label: '氛围打卡',
        periodLabel: '适合拍照出片',
        headline: '这家太出片了',
        subheadline: '氛围感拉满',
        offer: '打卡送饮品',
        note: '建议傍晚光线',
        styleId: 'fresh',
      },
      {
        id: 'hidden_menu',
        label: '隐藏菜单',
        periodLabel: '本地人私藏',
        headline: '隐藏菜单必点',
        subheadline: '懂行的才知道',
        offer: '探店套餐',
        note: '可向店员询问',
      },
      {
        id: 'value',
        label: '人均友好',
        periodLabel: '高性价比',
        headline: '人均不过百',
        subheadline: '学生党/打工人友好',
        offer: '人均¥68',
        note: '真实消费参考',
      },
      {
        id: 'must_try',
        label: '必点推荐',
        periodLabel: '招牌必吃',
        headline: '本地人必点TOP3',
        subheadline: '回头客最多',
        offer: '',
        note: '跟着点不踩雷',
      },
    ],
  },
  member_recharge: {
    pickerLabel: '储值档位',
    options: [
      {
        id: 'tier_300',
        label: '充300送50',
        periodLabel: '长期有效',
        headline: '充300送50',
        subheadline: '老客专享回馈',
        offer: '到账350元',
        timeRange: '长期有效',
        note: '可与活动同享',
        styleId: 'premium',
      },
      {
        id: 'tier_500',
        label: '充500送100',
        periodLabel: '长期有效',
        headline: '充500送100',
        subheadline: '到店核销',
        offer: '到账600元',
        timeRange: '长期有效',
      },
      {
        id: 'tier_1000',
        label: '充1000送250',
        periodLabel: 'VIP专享',
        headline: '充1000送250',
        subheadline: '赠招牌菜1份',
        offer: '到账1250元',
        timeRange: '长期有效',
        note: '限量100名',
      },
    ],
  },
  daily_sign: {
    pickerLabel: '日签主题',
    options: [
      {
        id: 'morning',
        label: '早安营业',
        periodLabel: '今日正常营业',
        headline: '早安 · 今日营业中',
        subheadline: '欢迎预约',
        timeRange: '今日全天',
        styleId: 'minimal',
      },
      {
        id: 'weekend',
        label: '周末愉快',
        periodLabel: '周末欢迎到店',
        headline: '周末愉快',
        subheadline: '周末不加价',
        timeRange: '周六日',
      },
      {
        id: 'rain',
        label: '雨天提醒',
        periodLabel: '雨天路滑',
        headline: '雨天路滑 · 慢走',
        subheadline: '外卖照常',
        timeRange: '今日',
        note: '出行注意安全',
      },
      {
        id: 'recommend',
        label: '今日推荐',
        periodLabel: '主厨推荐',
        headline: '今日推荐',
        subheadline: '新鲜到货',
        offer: '限时特价',
        timeRange: '今日',
      },
    ],
  },
  product_hero: {
    pickerLabel: '单品类型',
    options: [
      {
        id: 'signature_dish',
        label: '招牌菜',
        periodLabel: '镇店之宝',
        headline: '招牌必点',
        subheadline: '销量领先',
        offer: '¥28',
        styleId: 'ecommerce',
      },
      {
        id: 'new_product',
        label: '新品上市',
        periodLabel: '限时尝鲜',
        headline: '新品首发',
        subheadline: '限时尝鲜价',
        offer: '第二份半价',
        timeRange: '上新首周',
      },
      {
        id: 'seasonal',
        label: '时令限定',
        periodLabel: '本季限定',
        headline: '时令限定',
        subheadline: '错过等一年',
        offer: '限量供应',
        timeRange: '本季',
        styleId: 'fresh',
      },
      {
        id: 'drink',
        label: '饮品甜品',
        periodLabel: '下午茶时段',
        headline: '下午茶必点',
        subheadline: '拍照好看',
        offer: '¥18起',
        timeRange: '14:00—17:00',
      },
    ],
  },
  logo_brand: {
    pickerLabel: '标识用途',
    options: [
      {
        id: 'avatar',
        label: '门店头像',
        periodLabel: '1:1 圆形',
        headline: '{store}',
        subheadline: '',
        note: '适合微信/点评头像',
        styleId: 'minimal',
      },
      {
        id: 'signboard',
        label: '门头招牌',
        periodLabel: '横版大字',
        headline: '{store}',
        note: '适合线下门头',
      },
      {
        id: 'wechat',
        label: '微信头像',
        periodLabel: '简洁识别',
        headline: '{store}',
        subheadline: '本地生活',
        note: '小尺寸清晰可读',
        styleId: 'minimal',
      },
    ],
  },
  menu_board: {
    pickerLabel: '菜单类型',
    options: [
      {
        id: 'full',
        label: '全天菜单',
        periodLabel: '全时段',
        headline: '价目表',
        timeRange: '全天供应',
        styleId: 'lively',
      },
      {
        id: 'lunch',
        label: '午市价目',
        periodLabel: '11:00—14:00',
        headline: '午市菜单',
        timeRange: '11:00—14:00',
      },
      {
        id: 'dinner',
        label: '晚市价目',
        periodLabel: '17:00—22:00',
        headline: '晚市菜单',
        timeRange: '17:00—22:00',
      },
      {
        id: 'set',
        label: '套餐专区',
        periodLabel: '套餐组合',
        headline: '超值套餐',
        subheadline: '组合更省',
        note: '含多道招牌',
      },
    ],
  },
  platform_carousel_five: {
    pickerLabel: '三连图主题',
    options: [
      {
        id: 'opening',
        label: '开业上新',
        periodLabel: '连续场景 · 头图轮播',
        headline: '全新开业',
        subheadline: '',
        styleId: 'premium',
      },
      {
        id: 'quality',
        label: '品质服务',
        periodLabel: '环境叙事 · 信任感',
        headline: '品质服务',
        subheadline: '',
        styleId: 'premium',
      },
      {
        id: 'promo',
        label: '团购促销',
        periodLabel: '需自行填写价格',
        headline: '限时团购',
        subheadline: '',
        offer: '',
        styleId: 'ecommerce',
      },
    ],
  },
  platform_detail_page: {
    pickerLabel: '详情图风格',
    options: [
      {
        id: 'luxury',
        label: '轻奢质感',
        periodLabel: '大图+中英标题',
        headline: '提升服务品质',
        subheadline: 'IMPROVE SERVICE QUALITY',
        styleId: 'premium',
      },
      {
        id: 'warm',
        label: '温馨治愈',
        periodLabel: '慢生活+放松氛围',
        headline: '放慢脚步 享受生活',
        subheadline: '预约到店更省心',
        styleId: 'fresh',
      },
      {
        id: 'deal',
        label: '团购转化',
        periodLabel: '价格+抢购引导',
        headline: '限时特惠',
        subheadline: '立即抢购',
        offer: '¥99',
        styleId: 'ecommerce',
      },
    ],
  },
}

const INDUSTRY_PLAYBOOK_VARIANT_OVERRIDES = {
  leisure: {
    store_visit: {
      pickerLabel: '种草角度',
      options: [
        {
          id: 'ambiance',
          label: '氛围打卡',
          periodLabel: '适合拍照出片',
          headline: '这里太出片了',
          subheadline: '氛围感拉满',
          offer: '打卡送饮品',
          note: '建议傍晚光线',
          styleId: 'fresh',
        },
        {
          id: 'play_pack',
          label: '畅玩套餐',
          periodLabel: '团购性价比高',
          headline: '畅玩套餐超值',
          subheadline: '周末开黑首选',
          offer: '2小时¥88',
          note: '好友同行更划算',
        },
        {
          id: 'social',
          label: '社交聚会',
          periodLabel: '好友局首选',
          headline: '周末好友局',
          subheadline: '聚会放松好去处',
          offer: '4人团¥199',
          note: '提前预约更省心',
        },
        {
          id: 'local_hot',
          label: '本地潮店',
          periodLabel: '年轻人打卡地',
          headline: '本地潮玩打卡地',
          subheadline: '懂行的才知道',
          offer: '',
          note: '本地人私藏',
        },
      ],
    },
    group_buy_new: {
      pickerLabel: '团购规格',
      options: [
        {
          id: 'double_play',
          label: '双人畅玩',
          periodLabel: '2人适用',
          headline: '双人畅玩套餐',
          subheadline: '周末通用',
          offer: '¥99双人畅玩',
          timeRange: '周末通用',
          note: '免预约',
        },
        {
          id: 'group_4',
          label: '4人团',
          periodLabel: '3-4人适用',
          headline: '4人畅玩团',
          subheadline: '好友局必备',
          offer: '¥168/4人',
          timeRange: '午晚通用',
        },
        {
          id: 'weekday',
          label: '平日套餐',
          periodLabel: '周一至周五',
          headline: '平日畅玩特惠',
          subheadline: '工作日专享价',
          offer: '平日半价',
          timeRange: '周一至周五',
        },
        {
          id: 'weekend',
          label: '周末专场',
          periodLabel: '周六日',
          headline: '周末畅玩专场',
          subheadline: '不加价',
          offer: '¥199周末团',
          timeRange: '周六日',
        },
      ],
    },
    product_hero: {
      pickerLabel: '主推项目',
      options: [
        {
          id: 'signature',
          label: '招牌项目',
          periodLabel: '镇店王牌',
          headline: '招牌必玩',
          subheadline: '回头客最多',
          offer: '¥88起',
          styleId: 'fresh',
        },
        {
          id: 'new_experience',
          label: '新品体验',
          periodLabel: '限时尝鲜',
          headline: '新品首发',
          subheadline: '限时尝鲜价',
          offer: '体验价¥68',
          timeRange: '上新首周',
        },
        {
          id: 'limited',
          label: '限时优惠',
          periodLabel: '本季限定',
          headline: '限时特惠',
          subheadline: '售完即止',
          offer: '立减30元',
          timeRange: '本季',
        },
        {
          id: 'night_pack',
          label: '夜场套餐',
          periodLabel: '晚间时段',
          headline: '夜场畅玩',
          subheadline: '越夜越精彩',
          offer: '¥128夜场',
          timeRange: '18:00—24:00',
        },
      ],
    },
    flash_sale: {
      pickerLabel: '秒杀时段',
      options: [
        {
          id: 'tonight_8',
          label: '今晚8点',
          periodLabel: '今日 20:00—24:00',
          headline: '今晚8点秒杀',
          subheadline: '准时开抢',
          offer: '5折起',
          timeRange: '今日 20:00—24:00',
        },
        {
          id: 'weekend',
          label: '周末专场',
          periodLabel: '周六日全天',
          headline: '周末限时秒杀',
          offer: '立减30元',
          timeRange: '周六日 10:00—22:00',
        },
        {
          id: 'weekday',
          label: '平日闪购',
          periodLabel: '周一至周五',
          headline: '平日秒杀',
          subheadline: '工作日专享',
          offer: '买一送一',
          timeRange: '周一至周五',
        },
        {
          id: 'clearance',
          label: '清仓特惠',
          periodLabel: '售完即止',
          headline: '最后一批',
          offer: '3折起',
          timeRange: '售完即止',
        },
      ],
    },
    daily_sign: {
      pickerLabel: '日签主题',
      options: [
        {
          id: 'morning',
          label: '早安营业',
          periodLabel: '今日正常营业',
          headline: '早安 · 今日营业中',
          timeRange: '今日全天',
          styleId: 'minimal',
        },
        {
          id: 'weekend',
          label: '周末愉快',
          periodLabel: '周末欢迎到店',
          headline: '周末愉快',
          timeRange: '周六日',
        },
        {
          id: 'rain',
          label: '雨天提醒',
          periodLabel: '雨天路滑',
          headline: '雨天路滑 · 慢走',
          timeRange: '今日',
          note: '出行注意安全',
        },
        {
          id: 'recommend',
          label: '今日推荐',
          periodLabel: '店长推荐',
          headline: '今日推荐玩法',
          offer: '限时特价',
          timeRange: '今日',
        },
      ],
    },
    member_recharge: {
      pickerLabel: '储值档位',
      options: [
        {
          id: 'tier_300',
          label: '充300送50',
          periodLabel: '长期有效',
          headline: '充300送50',
          subheadline: '老客专享回馈',
          offer: '到账350元',
          timeRange: '长期有效',
          styleId: 'premium',
        },
        {
          id: 'tier_500',
          label: '充500送100',
          periodLabel: '长期有效',
          headline: '充500送100',
          offer: '到账600元',
          timeRange: '长期有效',
        },
        {
          id: 'tier_1000',
          label: '充1000送250',
          periodLabel: 'VIP专享',
          headline: '充1000送250',
          subheadline: '赠畅玩1次',
          offer: '到账1250元',
          timeRange: '长期有效',
          note: '限量100名',
        },
      ],
    },
  },
  beauty: {
    store_visit: {
      pickerLabel: '种草角度',
      options: [
        {
          id: 'ambiance',
          label: '氛围打卡',
          periodLabel: '环境高级感',
          headline: '这家店太高级了',
          subheadline: '轻奢氛围拉满',
          offer: '新客体验价',
          styleId: 'premium',
        },
        {
          id: 'before_after',
          label: '效果对比',
          periodLabel: '真实案例',
          headline: '效果看得见',
          subheadline: '专业技师操作',
          offer: '',
          note: '案例仅供参考',
        },
        {
          id: 'experience',
          label: '体验推荐',
          periodLabel: '新客首选',
          headline: '新客必试项目',
          subheadline: '口碑项目TOP1',
          offer: '体验价¥99',
        },
        {
          id: 'local_hot',
          label: '本地口碑',
          periodLabel: '回头客最多',
          headline: '本地人私藏美店',
          subheadline: '懂行的才知道',
          offer: '',
        },
      ],
    },
    group_buy_new: {
      pickerLabel: '套餐规格',
      options: [
        {
          id: 'single',
          label: '单人体验',
          periodLabel: '1人适用',
          headline: '单人护理套餐',
          subheadline: '含清洁+护理',
          offer: '体验价¥99',
          note: '需提前预约',
        },
        {
          id: 'double',
          label: '闺蜜同行',
          periodLabel: '2人适用',
          headline: '闺蜜同行套餐',
          subheadline: '同行更划算',
          offer: '双人¥168',
        },
        {
          id: 'course',
          label: '疗程卡',
          periodLabel: '多次护理',
          headline: '疗程卡特惠',
          subheadline: '长期护理更省',
          offer: '3次卡¥499',
        },
        {
          id: 'new_client',
          label: '新客专享',
          periodLabel: '限新客首单',
          headline: '新客三重礼',
          offer: '首单立减50',
          note: '限新客',
        },
      ],
    },
    product_hero: {
      pickerLabel: '主推项目',
      options: [
        {
          id: 'signature',
          label: '招牌项目',
          periodLabel: '镇店王牌',
          headline: '招牌必做',
          offer: '¥199单次',
          styleId: 'premium',
        },
        {
          id: 'new_service',
          label: '新品项目',
          periodLabel: '限时尝鲜',
          headline: '新品首发',
          offer: '体验价¥128',
        },
        {
          id: 'seasonal',
          label: '季节护理',
          periodLabel: '本季推荐',
          headline: '季节限定护理',
          offer: '限时8折',
        },
        {
          id: 'combo',
          label: '组合套餐',
          periodLabel: '多项目组合',
          headline: '焕肤组合',
          offer: '套餐¥299',
        },
      ],
    },
  },
  hotel: {
    store_visit: {
      pickerLabel: '种草角度',
      options: [
        {
          id: 'ambiance',
          label: '度假氛围',
          periodLabel: '适合拍照出片',
          headline: '度假感拉满',
          subheadline: '逃离城市计划',
          styleId: 'minimal',
        },
        {
          id: 'room_view',
          label: '房型景观',
          periodLabel: '窗外美景',
          headline: '窗外风景绝了',
          subheadline: '推窗见景',
        },
        {
          id: 'experience',
          label: '入住体验',
          periodLabel: '真实住客感受',
          headline: '入住体验满分',
          subheadline: '服务贴心',
        },
        {
          id: 'local_hot',
          label: '周边攻略',
          periodLabel: '本地人推荐',
          headline: '周边游玩攻略',
          offer: '',
        },
      ],
    },
    group_buy_new: {
      pickerLabel: '套餐规格',
      options: [
        {
          id: 'single_night',
          label: '单晚套餐',
          periodLabel: '1晚适用',
          headline: '单晚度假套餐',
          subheadline: '含双早',
          offer: '¥599/晚',
        },
        {
          id: 'two_nights',
          label: '连住两晚',
          periodLabel: '2晚适用',
          headline: '连住更省',
          offer: '两晚¥999',
        },
        {
          id: 'family',
          label: '家庭房',
          periodLabel: '亲子出行',
          headline: '家庭房特惠',
          offer: '家庭房¥799',
        },
        {
          id: 'weekend',
          label: '周末度假',
          periodLabel: '周六日',
          headline: '周末微度假',
          offer: '周末特惠',
        },
      ],
    },
    product_hero: {
      pickerLabel: '主推房型',
      options: [
        {
          id: 'signature',
          label: '招牌房型',
          periodLabel: '最受欢迎',
          headline: '招牌房型',
          offer: '¥599起',
        },
        {
          id: 'suite',
          label: '套房升级',
          periodLabel: '尊享体验',
          headline: '套房升级',
          offer: '限时升级',
        },
        {
          id: 'view_room',
          label: '景观房',
          periodLabel: '推窗见景',
          headline: '景观房特惠',
          offer: '¥699起',
        },
        {
          id: 'seasonal',
          label: '季节限定',
          periodLabel: '本季推荐',
          headline: '季节限定礼遇',
          offer: '限时优惠',
        },
      ],
    },
  },
  pet: {
    store_visit: {
      pickerLabel: '种草角度',
      options: [
        {
          id: 'ambiance',
          label: '萌宠打卡',
          periodLabel: '治愈氛围',
          headline: '主子太可爱了',
          subheadline: '萌宠治愈',
          styleId: 'fresh',
        },
        {
          id: 'service',
          label: '服务体验',
          periodLabel: '洗护美容',
          headline: '洗护体验满分',
          subheadline: '专业护理',
        },
        {
          id: 'product',
          label: '用品推荐',
          periodLabel: '铲屎官必囤',
          headline: '铲屎官必囤',
          offer: '正品保障',
        },
        {
          id: 'local_hot',
          label: '本地口碑',
          periodLabel: '回头客最多',
          headline: '本地萌宠好店',
        },
      ],
    },
    group_buy_new: {
      pickerLabel: '套餐规格',
      options: [
        {
          id: 'wash',
          label: '洗护套餐',
          periodLabel: '洗澡+护理',
          headline: '洗护套餐',
          offer: '洗护¥68起',
        },
        {
          id: 'beauty',
          label: '美容套餐',
          periodLabel: '洗澡+美容',
          headline: '美容套餐',
          offer: '美容¥128',
        },
        {
          id: 'new_client',
          label: '新客首单',
          periodLabel: '限新客',
          headline: '新客首单特惠',
          offer: '立减20元',
        },
        {
          id: 'member',
          label: '会员套餐',
          periodLabel: '长期护理',
          headline: '会员护理卡',
          offer: '3次卡¥299',
        },
      ],
    },
    product_hero: {
      pickerLabel: '主推商品',
      options: [
        {
          id: 'food',
          label: '主粮用品',
          periodLabel: '正品保障',
          headline: '爆款主粮',
          offer: '¥89起',
        },
        {
          id: 'snack',
          label: '零食玩具',
          periodLabel: '萌宠最爱',
          headline: '零食玩具TOP1',
          offer: '第二件半价',
        },
        {
          id: 'health',
          label: '保健护理',
          periodLabel: '健康养护',
          headline: '健康护理',
          offer: '限时特价',
        },
        {
          id: 'new_arrival',
          label: '新品上架',
          periodLabel: '限时尝鲜',
          headline: '新品首发',
          offer: '上新特惠',
        },
      ],
    },
  },
  education: {
    group_buy_new: {
      pickerLabel: '课程规格',
      options: [
        {
          id: 'trial',
          label: '试听课',
          periodLabel: '限新学员',
          headline: '免费试听课',
          offer: '试学0元',
        },
        {
          id: 'single',
          label: '单次体验',
          periodLabel: '1次课时',
          headline: '单次体验课',
          offer: '体验价¥99',
        },
        {
          id: 'package',
          label: '课时包',
          periodLabel: '多次课时',
          headline: '课时包特惠',
          offer: '10课时¥999',
        },
        {
          id: 'group_buy',
          label: '团报优惠',
          periodLabel: '多人同报',
          headline: '团报更省',
          offer: '团报8折',
        },
      ],
    },
    product_hero: {
      pickerLabel: '主推课程',
      options: [
        {
          id: 'signature',
          label: '王牌课程',
          periodLabel: '口碑TOP1',
          headline: '王牌课程',
          offer: '限时体验',
        },
        {
          id: 'summer',
          label: '假期集训',
          periodLabel: '寒暑假',
          headline: '假期集训营',
          offer: '早鸟价',
        },
        {
          id: 'new_class',
          label: '新开班级',
          periodLabel: '限额招生',
          headline: '新开班招生',
          offer: '报名减300',
        },
        {
          id: 'one_on_one',
          label: '1对1辅导',
          periodLabel: '个性化',
          headline: '1对1辅导',
          offer: '咨询报价',
        },
      ],
    },
    daily_sign: {
      pickerLabel: '日签主题',
      options: [
        {
          id: 'morning',
          label: '开课提醒',
          periodLabel: '今日正常上课',
          headline: '今日正常上课',
          timeRange: '今日',
        },
        {
          id: 'weekend',
          label: '周末班',
          periodLabel: '周末课程',
          headline: '周末班开课',
          timeRange: '周六日',
        },
        {
          id: 'holiday',
          label: '假期通知',
          periodLabel: '调课安排',
          headline: '假期调课通知',
          timeRange: '假期',
        },
        {
          id: 'recommend',
          label: '今日推荐',
          periodLabel: '名师推荐',
          headline: '今日推荐课程',
          timeRange: '今日',
        },
      ],
    },
  },
}

function getPlaybookVariantConfig(playbookId, industryId) {
  const baseCfg = PLAYBOOK_VARIANT_CONFIGS[playbookId] || null
  if (!industryId || industryId === 'catering') return baseCfg
  const override = INDUSTRY_PLAYBOOK_VARIANT_OVERRIDES[industryId] && INDUSTRY_PLAYBOOK_VARIANT_OVERRIDES[industryId][playbookId]
  return override || baseCfg
}

function resolvePlaybookVariant(playbookId, variantId, industryId) {
  const cfg = getPlaybookVariantConfig(playbookId, industryId)
  if (!cfg || !variantId) return null
  return cfg.options.find((o) => o.id === variantId) || null
}

module.exports = {
  getPlaybookVariantConfig,
  resolvePlaybookVariant,
}
