/** 自动生成：require 引用确保上传/体验版包含全部封面 JPEG（勿手改） */
const byPath = {
  'platforms/channels-1.jpg': require('./platforms/channels-1.jpg'),
  'platforms/channels-2.jpg': require('./platforms/channels-2.jpg'),
  'platforms/channels-3.jpg': require('./platforms/channels-3.jpg'),
  'platforms/dianping-1.jpg': require('./platforms/dianping-1.jpg'),
  'platforms/dianping-2.jpg': require('./platforms/dianping-2.jpg'),
  'platforms/dianping-3.jpg': require('./platforms/dianping-3.jpg'),
  'platforms/douyin-1.jpg': require('./platforms/douyin-1.jpg'),
  'platforms/douyin-2.jpg': require('./platforms/douyin-2.jpg'),
  'platforms/douyin-3.jpg': require('./platforms/douyin-3.jpg'),
  'platforms/kuaishou-1.jpg': require('./platforms/kuaishou-1.jpg'),
  'platforms/kuaishou-2.jpg': require('./platforms/kuaishou-2.jpg'),
  'platforms/kuaishou-3.jpg': require('./platforms/kuaishou-3.jpg'),
  'platforms/xiaohongshu-1.jpg': require('./platforms/xiaohongshu-1.jpg'),
  'platforms/xiaohongshu-2.jpg': require('./platforms/xiaohongshu-2.jpg'),
  'platforms/xiaohongshu-3.jpg': require('./platforms/xiaohongshu-3.jpg'),
  'tags/caijing-1.jpg': require('./tags/caijing-1.jpg'),
  'tags/caijing-2.jpg': require('./tags/caijing-2.jpg'),
  'tags/chongwu-1.jpg': require('./tags/chongwu-1.jpg'),
  'tags/chongwu-2.jpg': require('./tags/chongwu-2.jpg'),
  'tags/gaoxiao-1.jpg': require('./tags/gaoxiao-1.jpg'),
  'tags/gaoxiao-2.jpg': require('./tags/gaoxiao-2.jpg'),
  'tags/jiaju-1.jpg': require('./tags/jiaju-1.jpg'),
  'tags/jiaju-2.jpg': require('./tags/jiaju-2.jpg'),
  'tags/jiankang-1.jpg': require('./tags/jiankang-1.jpg'),
  'tags/jiankang-2.jpg': require('./tags/jiankang-2.jpg'),
  'tags/jiaoyu-1.jpg': require('./tags/jiaoyu-1.jpg'),
  'tags/jiaoyu-2.jpg': require('./tags/jiaoyu-2.jpg'),
  'tags/lvyou-1.jpg': require('./tags/lvyou-1.jpg'),
  'tags/lvyou-2.jpg': require('./tags/lvyou-2.jpg'),
  'tags/meishi-1.jpg': require('./tags/meishi-1.jpg'),
  'tags/meishi-2.jpg': require('./tags/meishi-2.jpg'),
  'tags/meizhuang-1.jpg': require('./tags/meizhuang-1.jpg'),
  'tags/meizhuang-2.jpg': require('./tags/meizhuang-2.jpg'),
  'tags/minsheng-1.jpg': require('./tags/minsheng-1.jpg'),
  'tags/minsheng-2.jpg': require('./tags/minsheng-2.jpg'),
  'tags/muying-1.jpg': require('./tags/muying-1.jpg'),
  'tags/muying-2.jpg': require('./tags/muying-2.jpg'),
  'tags/qiche-1.jpg': require('./tags/qiche-1.jpg'),
  'tags/qiche-2.jpg': require('./tags/qiche-2.jpg'),
  'tags/qinggan-1.jpg': require('./tags/qinggan-1.jpg'),
  'tags/qinggan-2.jpg': require('./tags/qinggan-2.jpg'),
  'tags/qita-1.jpg': require('./tags/qita-1.jpg'),
  'tags/qita-2.jpg': require('./tags/qita-2.jpg'),
  'tags/shenghuo-1.jpg': require('./tags/shenghuo-1.jpg'),
  'tags/shenghuo-2.jpg': require('./tags/shenghuo-2.jpg'),
  'tags/sheying-1.jpg': require('./tags/sheying-1.jpg'),
  'tags/sheying-2.jpg': require('./tags/sheying-2.jpg'),
  'tags/shuma-1.jpg': require('./tags/shuma-1.jpg'),
  'tags/shuma-2.jpg': require('./tags/shuma-2.jpg'),
  'tags/tiyu-1.jpg': require('./tags/tiyu-1.jpg'),
  'tags/tiyu-2.jpg': require('./tags/tiyu-2.jpg'),
  'tags/wenhua-1.jpg': require('./tags/wenhua-1.jpg'),
  'tags/wenhua-2.jpg': require('./tags/wenhua-2.jpg'),
  'tags/xingqu-1.jpg': require('./tags/xingqu-1.jpg'),
  'tags/xingqu-2.jpg': require('./tags/xingqu-2.jpg'),
  'tags/yingshi-1.jpg': require('./tags/yingshi-1.jpg'),
  'tags/yingshi-2.jpg': require('./tags/yingshi-2.jpg'),
  'tags/youxi-1.jpg': require('./tags/youxi-1.jpg'),
  'tags/youxi-2.jpg': require('./tags/youxi-2.jpg'),
  'tags/yule-1.jpg': require('./tags/yule-1.jpg'),
  'tags/yule-2.jpg': require('./tags/yule-2.jpg'),
  'tags/yundong-1.jpg': require('./tags/yundong-1.jpg'),
  'tags/yundong-2.jpg': require('./tags/yundong-2.jpg'),
  'tags/zhishi-1.jpg': require('./tags/zhishi-1.jpg'),
  'tags/zhishi-2.jpg': require('./tags/zhishi-2.jpg'),
}

function urlByPath(rel) {
  const key = String(rel || '').replace(/^\/+/, '')
  return byPath[key] || ''
}

module.exports = byPath
module.exports.byPath = byPath
module.exports.urlByPath = urlByPath
